export const TOOLS = {
  LINE: "LINE",
  ARROW: "ARROW",
  RECTANGLE: "RECTANGLE",
  CIRCLE: "CIRCLE",
  TEXT: "TEXT",
  BRUSH: "BRUSH",
  ERASE: "ERASE",
  UNDO: "UNDO",
  REDO: "REDO",
};

export const TOOLBOX_ACTIONS = {
  CHANGE_STROKE: "CHANGE_STROKE",
  CHANGE_FILL: "CHANGE_FILL",
  CHANGE_SIZE: "CHANGE_SIZE",
};

export const COLORS = {
  BLACK: "#000000",
  RED: "#ff0000",
  GREEN: "#00ff00",
  BLUE: "#0000ff",
  ORANGE: "#ffa500",
  YELLOW: "#ffff00",
  WHITE: "#ffffff",
};

export const TOOL_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  DRAW_DOWN: "DRAW_DOWN",
  DRAW_UP: "DRAW_UP",
  DRAW_MOVE: "DRAW_MOVE",
  CHANGE_TA: "CHANGE_TA_STATE",
  CHANGE_TEXT: "CHANGE_TEXT",
  UNDO: "UNDO",
  REDO: "REDO",
};

export const TA_STATES = {
  NONE: "NONE",
  HOLDING: "HOLDING",
  WRITING: "WRITING",
};

export const FILL_TOOL_TYPES = [TOOLS.RECTANGLE, TOOLS.CIRCLE];
export const STROKE_TOOL_TYPES = [TOOLS.BRUSH, TOOLS.LINE, TOOLS.ARROW, TOOLS.RECTANGLE, TOOLS.CIRCLE, TOOLS.TEXT];
export const SIZE_TOOL_TYPES = [TOOLS.LINE, TOOLS.ARROW, TOOLS.RECTANGLE, TOOLS.CIRCLE, TOOLS.TEXT];
export const ELEMENT_ERASE_THRESHOLD = 0.1;

